apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-app.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sample-app.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
{{- with .Values.configmaps }}        
        volumeMounts:
        {{- range . }}
        - name: {{ .name }}
          mountPath: /etc/myapp
        {{- end }}
{{- end }}
        env:
        - name: MYAPP_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MYAPP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MYAPP_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
{{- with .Values.configmaps }}                 
      volumes:
        {{- range . }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
{{- end }}